spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: sa-east-1
      auto: false
    credentials:
      access-key: AKIAXEG426BPOWIXKO5W
      secret-key: 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
    end-point:
      uri: https://sqs.sa-east-1.amazonaws.com/490089410654/local-queue-wgs

